version: "3.1"
services:
    app:
        build: .
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo
        env_file:
            - .env
    mongo:
        image: mongo
        restart: always
        env_file:
            - .env