version: "3.1"
volumes:
    mongo_data:
services:
    app:
        build: .
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo
        env_file:
            - .env
    mongo:
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=abizitate
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017-27019:27017-27019