version: "3.1"
services:
    app:
        build: .
        ports:
            - 8080:8080
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: abifag # This is military grade security
            MONGO_INITDB_ROOT_PASSWORD: abifag # Pretty sure theres an xkcd cartoon about this kinda shit